version = 1

exclude_patterns = [
  "dist",
  "bundle.js"
]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "shell"
enabled = true